.TH "test_parser.c" 9 "Version pulgamecanica" "42sh Tests" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_parser.c \- Unit tests for the 42sh parser module\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'minunit\&.h'\fP
.br
\fR#include 'parser\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Unit tests for the 42sh parser module\&. 


.SS "How to enable"
Add \fR-DTEST_PARSER_ENABLED\fP to \fRTEST_FLAGS\fP in the root Makefile and declare \fRtest_parser_suite\fP in \fBtest_runner\&.c\fP\&. Once all assertions are permanently green, remove the \fR#ifdef\fP guards and the \fR-D\fP flag per the workflow described in \fBtest_runner\&.c\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh Tests from the source code\&.
.SH SEE ALSO
.BR minunit.h (9),
.BR test_btree.c (9),
.BR test_dlist.c (9),
.BR test_executor.c (9),
.BR test_history.c (9),
.BR test_lexer.c (9),
.BR test_list.c (9),
.BR test_runner.c (9),
.BR test_stubs.c (9)
