.TH "test_executor.c" 9 "Version pulgamecanica" "42sh Tests" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_executor.c \- Comprehensive test suite for the executor module\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'minunit\&.h'\fP
.br
\fR#include '\&.\&./includes/42sh\&.h'\fP
.br
\fR#include '\&.\&./includes/executor\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <sys/wait\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Comprehensive test suite for the executor module\&. 

Tests: exec_utils, command_search, redirections, heredoc, logical operators, pipeline, subshell, block, background, simple command execution (builtins + externals)\&.

.PP
Uses functional stubs from \fBtest_stubs\&.c\fP for dependencies\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh Tests from the source code\&.
.SH SEE ALSO
.BR minunit.h (9),
.BR test_btree.c (9),
.BR test_dlist.c (9),
.BR test_history.c (9),
.BR test_lexer.c (9),
.BR test_list.c (9),
.BR test_parser.c (9),
.BR test_runner.c (9),
.BR test_stubs.c (9)
