.TH "test_stubs.c" 9 "Version pulgamecanica" "42sh Tests" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_stubs.c \- Functional stubs for modules the executor depends on\&.  

.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./includes/42sh\&.h'\fP
.br
\fR#include '\&.\&./includes/builtins\&.h'\fP
.br
\fR#include '\&.\&./includes/expander\&.h'\fP
.br
\fR#include '\&.\&./includes/executor\&.h'\fP
.br
\fR#include '\&.\&./includes/signals\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Functional stubs for modules the executor depends on\&. 

Provides minimal but working implementations of variables, builtins, expander, and signals so that executor tests can link and run\&. These stubs are only compiled into the test binary (42sh_test)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh Tests from the source code\&.
.SH SEE ALSO
.BR minunit.h (9),
.BR test_btree.c (9),
.BR test_dlist.c (9),
.BR test_executor.c (9),
.BR test_history.c (9),
.BR test_lexer.c (9),
.BR test_list.c (9),
.BR test_parser.c (9),
.BR test_runner.c (9)
