.TH "test_btree.c" 9 "Version pulgamecanica" "42sh Tests" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_btree.c \- Test suite for the binary tree (t_btree) implementation\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'minunit\&.h'\fP
.br
\fR#include '\&.\&./Libft/includes/libft\&.h'\fP
.br
\fR#include <stdlib\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Test suite for the binary tree (t_btree) implementation\&. 


.PP
\fBAuthor\fP
.RS 4
jguillem
.RE
.PP
Covers btree_insert_data(), btree_create_node(), btree_clear() 
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh Tests from the source code\&.
.SH SEE ALSO
.BR minunit.h (9),
.BR test_dlist.c (9),
.BR test_executor.c (9),
.BR test_history.c (9),
.BR test_lexer.c (9),
.BR test_list.c (9),
.BR test_parser.c (9),
.BR test_runner.c (9),
.BR test_stubs.c (9)
