.TH "includes/42sh.h" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/42sh.h \- Top-level header for the 42sh shell, includes all sub-systems and defines the central \fR\fBt_shell\fP\fP state struct\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <unistd\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <errno\&.h>\fP
.br
\fR#include <fcntl\&.h>\fP
.br
\fR#include <sys/types\&.h>\fP
.br
\fR#include <sys/wait\&.h>\fP
.br
\fR#include <sys/stat\&.h>\fP
.br
\fR#include <termios\&.h>\fP
.br
\fR#include <term\&.h>\fP
.br
\fR#include <readline/readline\&.h>\fP
.br
\fR#include <readline/history\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include 'history\&.h'\fP
.br
\fR#include 'libft\&.h'\fP
.br
\fR#include 'variables\&.h'\fP
.br
\fR#include 'job_control\&.h'\fP
.br
\fR#include 'signals\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBt_shell\fP"
.br
.RI "Central runtime state of the shell — one instance lives in \fRmain()\fP\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLST_VAR\fP(n)"
.br
.ti -1c
.RI "#define \fBLST_JOB\fP(n)"
.br
.ti -1c
.RI "#define \fBLST_ALIAS\fP(n)"
.br
.ti -1c
.RI "#define \fBLST_PROC\fP(n)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBvar_get_value\fP (\fBt_shell\fP *shell, const char *name)"
.br
.ti -1c
.RI "t_var * \fBvar_get\fP (\fBt_shell\fP *shell, const char *name)"
.br
.ti -1c
.RI "int \fBvar_set\fP (\fBt_shell\fP *shell, const char *name, const char *value)"
.br
.ti -1c
.RI "int \fBvar_unset\fP (\fBt_shell\fP *shell, const char *name)"
.br
.ti -1c
.RI "int \fBvar_export\fP (\fBt_shell\fP *shell, const char *name)"
.br
.ti -1c
.RI "char ** \fBvar_get_environ\fP (\fBt_shell\fP *shell)"
.br
.ti -1c
.RI "void \fBvar_init_from_environ\fP (\fBt_shell\fP *shell, char **envp)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Top-level header for the 42sh shell, includes all sub-systems and defines the central \fR\fBt_shell\fP\fP state struct\&. 


.PP
\fBAuthor\fP
.RS 4
wengzhang, jguillem, jspitz, pulgamecanica, zweng 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define LST_ALIAS( n)"
\fBValue:\fP
.nf
((t_alias *)(n)\->content)
.PP
.fi
Cast a \fRt_list\fP node's content to \fRt_alias *\fP\&. 
.SS "#define LST_JOB( n)"
\fBValue:\fP
.nf
((t_job *)(n)\->content)
.PP
.fi
Cast a \fRt_list\fP node's content to \fRt_job *\fP\&. 
.SS "#define LST_PROC( n)"
\fBValue:\fP
.nf
((t_process *)(n)\->content)
.PP
.fi
Cast a \fRt_list\fP node's content to \fRt_process *\fP\&. 
.SS "#define LST_VAR( n)"
\fBValue:\fP
.nf
((t_var *)(n)\->content)
.PP
.fi
Cast a \fRt_list\fP node's content to \fRt_var *\fP\&. 
.SH "Function Documentation"
.PP 
.SS "int var_export (\fBt_shell\fP * shell, const char * name)"
Mark variable \fRname\fP for export to child processes\&. 
.SS "t_var * var_get (\fBt_shell\fP * shell, const char * name)"
Get the \fRt_var\fP node for \fRname\fP, or NULL if unset\&. 
.SS "char ** var_get_environ (\fBt_shell\fP * shell)"
Return (and cache) the \fRNULL\fP-terminated \fRenvp\fP array for execve\&. 
.SS "char * var_get_value (\fBt_shell\fP * shell, const char * name)"
Get the value string of variable \fRname\fP, or NULL if unset\&. 
.SS "void var_init_from_environ (\fBt_shell\fP * shell, char ** envp)"
Populate \fRshell->variables\fP from the process's initial \fRenvp\fP\&. 
.SS "int var_set (\fBt_shell\fP * shell, const char * name, const char * value)"
Set (or create) variable \fRname\fP to \fRvalue\fP\&. Returns 0 on success\&. 
.SS "int var_unset (\fBt_shell\fP * shell, const char * name)"
Remove variable \fRname\fP\&. Returns 0 on success\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtin_history.c (9),
.BR builtins.h (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_logical.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR executor.h (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_command.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_heredoc.c (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_operator (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
