.TH "srcs/builtins/builtin_history.c" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/builtins/builtin_history.c \- Implementation of the history builtin command for the 42sh shell\&.  

.SH SYNOPSIS
.br
.PP
\fR#include '42sh\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBprint_entries\fP (HIST_ENTRY **list, int start, int end)"
.br
.RI "Print the command history list\&. "
.ti -1c
.RI "int \fBbuiltin_history\fP (struct s_shell *shell, int argc, char **argv)"
.br
.RI "display the command history list "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the history builtin command for the 42sh shell\&. 


.PP
\fBAuthor\fP
.RS 4
pulgamecanica
.RE
.PP
.SS "Notes"
.IP "\(bu" 2
history_list() returns a NULL-terminated array of HIST_ENTRY* (readline)\&.
.IP "\(bu" 2
history_base is the number assigned to the first entry (typically 1)\&.
.IP "\(bu" 2
history_length is the total number of entries currently in the list\&. 
.PP

.SH "Function Documentation"
.PP 
.SS "int builtin_history (struct s_shell * shell, int argc, char ** argv)"

.PP
display the command history list This function displays the command history list in a format similar to bash and ksh\&.

.PP
\fBParameters\fP
.RS 4
\fIshell\fP The shell context (not used in this function)\&. 
.br
\fIargc\fP The number of arguments passed to the history command\&. 
.br
\fIargv\fP The arguments passed to the history command\&. If a numeric argument is provided, it specifies how many of the most recent entries to display\&.
.RE
.PP
\fBReturns\fP
.RS 4
int Always returns 0\&. 
.RE
.PP

.SS "static void print_entries (HIST_ENTRY ** list, int start, int end)\fR [static]\fP"

.PP
Print the command history list\&. Prints all entries of the history

.PP
\fBParameters\fP
.RS 4
\fIlist\fP The list of history entries obtained from readline's history_list() 
.br
\fIstart\fP The starting index in the history list to print from 
.br
\fIend\fP The ending index in the history list to print to (exclusive) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR 42sh.h (9),
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtins.h (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_logical.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR executor.h (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_command.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_heredoc.c (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_operator (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
