.TH "includes/builtins.h" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/builtins.h \- defines the central \fR\fBt_shell\fP\fP state struct\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int(* \fBt_builtin_fn\fP) (struct s_shell *shell, int argc, char **argv)"
.br
.RI "Builtin function type\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_builtin_fn\fP \fBbuiltin_get\fP (const char *name)"
.br
.RI "Builtin registry\&. "
.ti -1c
.RI "int \fBbuiltin_history\fP (struct s_shell *shell, int argc, char **argv)"
.br
.RI "display the command history list "
.in -1c
.SH "Detailed Description"
.PP 
defines the central \fR\fBt_shell\fP\fP state struct\&. 


.PP
\fBAuthor\fP
.RS 4
zweng, pulgamecanica 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef int(* t_builtin_fn) (struct s_shell *shell, int argc, char **argv)"

.PP
Builtin function type\&. 
.PP
.RS 4
Forward declaration to avoid circular dependency with \fB42sh\&.h\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIshell\fP Pointer to the central shell state, for accessing variables, jobs, etc\&. 
.br
\fIargc\fP Argument count (number of elements in argv) 
.br
\fIargv\fP Argument vector (array of strings, with argv[0] being the command name) 
.RE
.PP
\fBReturns\fP
.RS 4
Exit status code (0 for success, non-zero for failure) 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBt_builtin_fn\fP builtin_get (const char * name)"

.PP
Builtin registry\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Name of the builtin function to retrieve 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the builtin function, or NULL if not found 
.RE
.PP

.SS "int builtin_history (struct s_shell * shell, int argc, char ** argv)"

.PP
display the command history list This function displays the command history list in a format similar to bash and ksh\&.

.PP
\fBParameters\fP
.RS 4
\fIshell\fP The shell context (not used in this function)\&. 
.br
\fIargc\fP The number of arguments passed to the history command\&. 
.br
\fIargv\fP The arguments passed to the history command\&. If a numeric argument is provided, it specifies how many of the most recent entries to display\&.
.RE
.PP
\fBReturns\fP
.RS 4
int Always returns 0\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR 42sh.h (9),
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtin_history.c (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_logical.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR executor.h (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_command.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_heredoc.c (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_operator (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
