.TH "includes/executor.h" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/executor.h \- defines the executor functions for handling AST nodes\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'ast\&.h'\fP
.br
\fR#include 'builtins\&.h'\fP
.br
\fR#include 'expander\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBexecutor_execute\fP (struct s_shell *shell, \fBt_ast\fP *ast)"
.br
.RI "Main dispatch function for executing AST nodes\&. "
.ti -1c
.RI "int \fBexecute_simple_command\fP (struct s_shell *shell, \fBt_cmd\fP *cmd)"
.br
.RI "Node-type executors\&. "
.ti -1c
.RI "int \fBsetup_redirections\fP (t_list *redirs, int saved_fds[3])"
.br
.RI "redirection setup "
.ti -1c
.RI "void \fBrestore_redirections\fP (int saved_fds[3])"
.br
.RI "Restore redirections\&. "
.ti -1c
.RI "int \fBsetup_heredoc\fP (\fBt_redir\fP *redir)"
.br
.RI "Heredoc setup\&. "
.ti -1c
.RI "char * \fBfind_command\fP (struct s_shell *shell, const char *name)"
.br
.RI "Command search (PATH) "
.ti -1c
.RI "void \fBexec_pipeline_external\fP (struct s_shell *shell, \fBt_cmd\fP *cmd)"
.br
.RI "Pipeline helper (called from pipe_child, does not return) "
.ti -1c
.RI "int \fBget_exit_status\fP (int wstatus)"
.br
.RI "get exit status from wait status "
.ti -1c
.RI "void \fBsplit_assignment\fP (const char *assign, char **name, char **value)"
.br
.RI "Split "NAME=value" at first '=' into separate name and value strings\&. "
.in -1c
.SH "Detailed Description"
.PP 
defines the executor functions for handling AST nodes\&. 


.PP
\fBAuthor\fP
.RS 4
zweng, pulgamecanica 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void exec_pipeline_external (struct s_shell * shell, \fBt_cmd\fP * cmd)"

.PP
Pipeline helper (called from pipe_child, does not return) 
.PP
\fBParameters\fP
.RS 4
\fIshell\fP Pointer to the central shell state 
.br
\fIcmd\fP Pointer to the command node 
.RE
.PP

.SS "int execute_simple_command (struct s_shell * shell, \fBt_cmd\fP * cmd)"

.PP
Node-type executors\&. 
.PP
\fBParameters\fP
.RS 4
\fIshell\fP Pointer to the central shell state 
.br
\fIast\fP Pointer to the AST node to execute 
.RE
.PP
\fBReturns\fP
.RS 4
Exit status code 
.RE
.PP

.SS "int executor_execute (struct s_shell * shell, \fBt_ast\fP * ast)"

.PP
Main dispatch function for executing AST nodes\&. 
.PP
\fBParameters\fP
.RS 4
\fIshell\fP Pointer to the central shell state 
.br
\fIast\fP Pointer to the AST node to execute 
.RE
.PP
\fBReturns\fP
.RS 4
Exit status code 
.RE
.PP

.SS "char * find_command (struct s_shell * shell, const char * name)"

.PP
Command search (PATH) 
.PP
\fBParameters\fP
.RS 4
\fIshell\fP Pointer to the central shell state 
.br
\fIname\fP Name of the command to search for 
.RE
.PP
\fBReturns\fP
.RS 4
Pointer to the found command, or NULL if not found 
.RE
.PP

.SS "int get_exit_status (int wstatus)"

.PP
get exit status from wait status 
.PP
\fBParameters\fP
.RS 4
\fIwstatus\fP Wait status code 
.RE
.PP
\fBReturns\fP
.RS 4
Exit status code
.RE
.PP
get exit status from wait status

.PP
.IP "\(bu" 2
Normal exit: WEXITSTATUS (0-255)
.PP

.PP
.IP "\(bu" 2
Killed by signal: 128 + signal number 
.PP
\fBParameters\fP
.RS 4
\fIwstatus\fP The waitpid status\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The shell exit code\&. 
.RE
.PP

.PP

.SS "void restore_redirections (int saved_fds[3])"

.PP
Restore redirections\&. 
.PP
\fBParameters\fP
.RS 4
\fIsaved_fds\fP Array of saved file descriptors
.RE
.PP
Restore redirections\&.

.PP
\fBParameters\fP
.RS 4
\fIsaved_fds\fP The array of saved file descriptors\&. 
.RE
.PP

.SS "int setup_heredoc (\fBt_redir\fP * redir)"

.PP
Heredoc setup\&. 
.PP
\fBParameters\fP
.RS 4
\fIredir\fP Pointer to the redirection node 
.RE
.PP
\fBReturns\fP
.RS 4
Exit status code
.RE
.PP
Heredoc setup\&.

.PP
the write end, close the write end, and return the read end fd\&. 
.PP
\fBParameters\fP
.RS 4
\fIredir\fP The redirection structure\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The read-end fd on success, -1 on error\&. 
.RE
.PP

.SS "int setup_redirections (t_list * redirs, int saved_fds[3])"

.PP
redirection setup 
.PP
\fBParameters\fP
.RS 4
\fIredirs\fP List of redirection nodes 
.br
\fIsaved_fds\fP Array to save original file descriptors 
.RE
.PP
\fBReturns\fP
.RS 4
Exit status code
.RE
.PP
redirection setup

.PP
If saved_fds is not NULL, save stdin/stdout/stderr first (for restore)\&. 
.PP
\fBParameters\fP
.RS 4
\fIredirs\fP The list of redirections\&. 
.br
\fIsaved_fds\fP The array to store the saved file descriptors\&. 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on error\&. 
.RE
.PP

.SS "void split_assignment (const char * assign, char ** name, char ** value)"

.PP
Split "NAME=value" at first '=' into separate name and value strings\&. Caller must free both *name and *value\&.

.PP
If no '=' found, *name = dup of assign, *value = dup of ""\&. 
.PP
\fBParameters\fP
.RS 4
\fIassign\fP The assignment string\&. 
.br
\fIname\fP The pointer to store the name\&. 
.br
\fIvalue\fP The pointer to store the value\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR 42sh.h (9),
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtin_history.c (9),
.BR builtins.h (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_logical.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_command.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_heredoc.c (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_operator (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
