.TH "srcs/executor/exec_logical.c" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/executor/exec_logical.c \- Logical command execution functionality for 42sh\&.  

.SH SYNOPSIS
.br
.PP
\fR#include '42sh\&.h'\fP
.br
\fR#include 'executor\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBexecute_and\fP (\fBt_shell\fP *shell, \fBt_ast\fP *ast)"
.br
.RI "Execute logical AND operation\&. "
.ti -1c
.RI "int \fBexecute_or\fP (\fBt_shell\fP *shell, \fBt_ast\fP *ast)"
.br
.RI "Execute logical OR operation\&. "
.ti -1c
.RI "int \fBexecute_sequence\fP (\fBt_shell\fP *shell, \fBt_ast\fP *ast)"
.br
.RI "Execute sequential commands\&. "
.in -1c
.SH "Detailed Description"
.PP 
Logical command execution functionality for 42sh\&. 


.PP
\fBAuthor\fP
.RS 4
wengzhang, pulgamecanica 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int execute_and (\fBt_shell\fP * shell, \fBt_ast\fP * ast)"

.PP
Execute logical AND operation\&. cmd1 && cmd2 : run right only if left succeeds (exit 0) 
.PP
\fBParameters\fP
.RS 4
\fIshell\fP The shell instance\&. 
.br
\fIast\fP The abstract syntax tree node\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The exit status of the operation\&. 
.RE
.PP

.SS "int execute_or (\fBt_shell\fP * shell, \fBt_ast\fP * ast)"

.PP
Execute logical OR operation\&. cmd1 || cmd2 : run right only if left fails (exit != 0) 
.PP
\fBParameters\fP
.RS 4
\fIshell\fP The shell instance\&. 
.br
\fIast\fP The abstract syntax tree node\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The exit status of the operation\&. 
.RE
.PP

.SS "int execute_sequence (\fBt_shell\fP * shell, \fBt_ast\fP * ast)"

.PP
Execute sequential commands\&. cmd1 ; cmd2 : run both, return status of right 
.PP
\fBParameters\fP
.RS 4
\fIshell\fP The shell instance\&. 
.br
\fIast\fP The abstract syntax tree node\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The exit status of the operation\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR 42sh.h (9),
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtin_history.c (9),
.BR builtins.h (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR executor.h (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_command.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_heredoc.c (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_operator (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
