.TH "srcs/parser/parser_command.c" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/parser/parser_command.c \- file for parse command  

.SH SYNOPSIS
.br
.PP
\fR#include 'parser\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBt_ast\fP * \fBast_new_command\fP (\fBt_cmd\fP *cmd)"
.br
.RI "allocate memory and define type for a NODE_COMMAND "
.ti -1c
.RI "\fBt_ast\fP * \fBparse_command\fP (\fBt_parser\fP *p)"
.br
.RI "handle (subshell) and (block) then parser command "
.ti -1c
.RI "static \fBt_cmd\fP * \fBcommand_init\fP (void)"
.br
.RI "initialize \fBt_cmd\fP struct "
.ti -1c
.RI "static void \fBparser_error_unexpected\fP (\fBt_parser\fP *p, \fBt_token\fP *token)"
.br
.RI "handle \fBt_parser\fP error field "
.ti -1c
.RI "static char ** \fBcommand_size\fP (\fBt_parser\fP *p, \fBt_cmd\fP *command)"
.br
.RI "allocate memory of \fBt_cmd\fP struct argv field "
.ti -1c
.RI "static \fBt_ast\fP * \fBcommand_build\fP (\fBt_parser\fP *p, \fBt_cmd\fP *command)"
.br
.RI "fill the \fBt_cmd\fP struct "
.ti -1c
.RI "static int \fBis_assignment\fP (char *str)"
.br
.RI "check for valid assignment "
.ti -1c
.RI "static void \fBparse_assignment\fP (\fBt_parser\fP *p, \fBt_cmd\fP *command)"
.br
.RI "append assignments to \fBt_cmd\fP struct "
.ti -1c
.RI "\fBt_ast\fP * \fBparse_simple_command\fP (\fBt_parser\fP *p)"
.br
.RI "handle commands and detect subshells "
.in -1c
.SH "Detailed Description"
.PP 
file for parse command 


.PP
\fBAuthor\fP
.RS 4
jguillem 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBt_ast\fP * ast_new_command (\fBt_cmd\fP * cmd)"

.PP
allocate memory and define type for a NODE_COMMAND AST construction helpers\&.

.PP
\fBParameters\fP
.RS 4
\fIcmd\fP struct s_cmd 
.RE
.PP
\fBReturns\fP
.RS 4
pointer on struct s_ast 
.RE
.PP

.SS "static \fBt_ast\fP * command_build (\fBt_parser\fP * p, \fBt_cmd\fP * command)\fR [static]\fP"

.PP
fill the \fBt_cmd\fP struct 
.PP
\fBParameters\fP
.RS 4
\fIp\fP \fBt_parser\fP struct 
.br
\fIcommand\fP \fBt_cmd\fP struct 
.RE
.PP
\fBReturns\fP
.RS 4
\fBt_ast\fP struct 
.RE
.PP

.SS "static char ** command_size (\fBt_parser\fP * p, \fBt_cmd\fP * command)\fR [static]\fP"

.PP
allocate memory of \fBt_cmd\fP struct argv field 
.PP
\fBParameters\fP
.RS 4
\fIp\fP \fBt_parser\fP struct 
.br
\fIcommand\fP \fBt_cmd\fP struct 
.RE
.PP
\fBReturns\fP
.RS 4
char **argv 
.RE
.PP

.SS "static int is_assignment (char * str)\fR [static]\fP"

.PP
check for valid assignment 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP char * 
.RE
.PP
\fBReturns\fP
.RS 4
0 | 1 
.RE
.PP

.SS "static void parse_assignment (\fBt_parser\fP * p, \fBt_cmd\fP * command)\fR [static]\fP"

.PP
append assignments to \fBt_cmd\fP struct 
.PP
\fBParameters\fP
.RS 4
\fIp\fP \fBt_parser\fP struct 
.br
\fIcommand\fP \fBt_cmd\fP struct 
.RE
.PP

.SS "\fBt_ast\fP * parse_command (\fBt_parser\fP * p)"

.PP
handle (subshell) and (block) then parser command 
.PP
\fBParameters\fP
.RS 4
\fIp\fP \fBt_parser\fP struct 
.RE
.PP
\fBReturns\fP
.RS 4
\fBt_ast\fP struct 
.RE
.PP

.SS "\fBt_ast\fP * parse_simple_command (\fBt_parser\fP * p)"

.PP
handle commands and detect subshells 
.PP
\fBParameters\fP
.RS 4
\fIp\fP struct s_parser 
.RE
.PP
\fBReturns\fP
.RS 4
a pointer on a struct s_ast 
.RE
.PP

.SS "static void parser_error_unexpected (\fBt_parser\fP * p, \fBt_token\fP * token)\fR [static]\fP"

.PP
handle \fBt_parser\fP error field 
.PP
\fBParameters\fP
.RS 4
\fIp\fP \fBt_parser\fP struct 
.br
\fItoken\fP \fBt_token\fP struct 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR 42sh.h (9),
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtin_history.c (9),
.BR builtins.h (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_logical.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR executor.h (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_heredoc.c (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_operator (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
