.TH "srcs/parser/parser_heredoc.c" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srcs/parser/parser_heredoc.c \- file to handle heredoc  

.SH SYNOPSIS
.br
.PP
\fR#include 'parser\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static char * \fBread_heredoc\fP (const char *delimiter, const char *prompt)"
.br
.RI "read the user input and store each line "
.ti -1c
.RI "static void \fBread_heredoc_from_pipe\fP (\fBt_redir\fP *redir, int pipefd[2])"
.br
.RI "read from the pipe out "
.ti -1c
.RI "static int \fBfork_heredoc\fP (\fBt_redir\fP *redir)"
.br
.RI "create a fork for the heredoc collecting "
.ti -1c
.RI "static int \fBcollect_heredocs_from_list\fP (t_list *lst)"
.br
.RI "helper function for collect heredocs from command or subshell "
.ti -1c
.RI "static int \fBcollect_heredocs_from_command\fP (\fBt_cmd\fP *cmd)"
.br
.RI "collect redirections of commands "
.ti -1c
.RI "static int \fBcollect_heredocs_from_group\fP (\fBt_group\fP *group)"
.br
.RI "collect redirections of group "
.ti -1c
.RI "void \fBheredoc_expand_config\fP (\fBt_redir\fP *redir)"
.br
.RI "fill the heredoc_delim and heredoc_quoted fields of the \fBt_redir\fP struct "
.ti -1c
.RI "static int \fBast_walk\fP (\fBt_ast\fP *ast, \fBt_shell\fP *shell)"
.br
.RI "traverses the ast tree and collect heredocs content, stopping on SIGINT "
.ti -1c
.RI "int \fBparser_collect_heredocs\fP (\fBt_ast\fP *ast, \fBt_shell\fP *shell)"
.br
.RI "stop ast walking and collect heredoc on SIGINT "
.in -1c
.SH "Detailed Description"
.PP 
file to handle heredoc 


.PP
\fBAuthor\fP
.RS 4
jguillem 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "static int ast_walk (\fBt_ast\fP * ast, \fBt_shell\fP * shell)\fR [static]\fP"

.PP
traverses the ast tree and collect heredocs content, stopping on SIGINT 
.PP
\fBParameters\fP
.RS 4
\fIast\fP : a pointer on a struct s_ast 
.br
\fIshell\fP : the shell struct 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on SIGINT 
.RE
.PP

.SS "static int collect_heredocs_from_command (\fBt_cmd\fP * cmd)\fR [static]\fP"

.PP
collect redirections of commands 
.PP
\fBParameters\fP
.RS 4
\fIcmd\fP : struct s_cmd pointer 
.RE
.PP

.SS "static int collect_heredocs_from_group (\fBt_group\fP * group)\fR [static]\fP"

.PP
collect redirections of group 
.PP
\fBParameters\fP
.RS 4
\fIgroup\fP : struct s_group pointer 
.RE
.PP

.SS "static int collect_heredocs_from_list (t_list * lst)\fR [static]\fP"

.PP
helper function for collect heredocs from command or subshell 
.PP
\fBParameters\fP
.RS 4
\fIlst\fP : a struct s_list pointer
.RE
.PP
store redirections 
.SS "static int fork_heredoc (\fBt_redir\fP * redir)\fR [static]\fP"

.PP
create a fork for the heredoc collecting 
.PP
\fBParameters\fP
.RS 4
\fIredir\fP pointer on a struct s_redir
.RE
.PP
in order to catch SIGINT only at the heredoc level 
.PP
\fBReturns\fP
.RS 4
0 | -1 
.RE
.PP

.SS "void heredoc_expand_config (\fBt_redir\fP * redir)"

.PP
fill the heredoc_delim and heredoc_quoted fields of the \fBt_redir\fP struct 
.PP
\fBParameters\fP
.RS 4
\fIredir\fP : \fBt_redir\fP struct 
.RE
.PP

.SS "int parser_collect_heredocs (\fBt_ast\fP * ast, \fBt_shell\fP * shell)"

.PP
stop ast walking and collect heredoc on SIGINT walk the AST after parsing and read heredoc content

.PP
\fBParameters\fP
.RS 4
\fIast\fP : struct s_ast pointer 
.br
\fIshell\fP : struct s_shell pointer 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on SIGINT 
.RE
.PP

.SS "static char * read_heredoc (const char * delimiter, const char * prompt)\fR [static]\fP"

.PP
read the user input and store each line 
.PP
\fBParameters\fP
.RS 4
\fIdelimiter\fP : const char pointer of the string representing EOF 
.br
\fIprompt\fP : the prompt symbol of the heredoc 
.RE
.PP
\fBReturns\fP
.RS 4
a char pointer on the content of the heredoc 
.RE
.PP

.SS "static void read_heredoc_from_pipe (\fBt_redir\fP * redir, int pipefd[2])\fR [static]\fP"

.PP
read from the pipe out 
.PP
\fBParameters\fP
.RS 4
\fIredir\fP pointer on a struct s_redir 
.br
\fIpipefd\fP the 2 ends of the pipe 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR 42sh.h (9),
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtin_history.c (9),
.BR builtins.h (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_logical.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR executor.h (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_command.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_operator (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
