.TH "t_operator" 9 "Version pulgamecanica" "42sh" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_operator \- Struct representing a shell token\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <lexer\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBliteral\fP"
.br
.ti -1c
.RI "\fBt_token_type\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct representing a shell token\&. 

This struct holds the type of the token, its raw value (with quotes preserved for later expansion), and an optional io_number for redirection tokens\&. 
.SH "Field Documentation"
.PP 
.SS "const char* t_operator::literal"
The literal string of the operator (e\&.g\&., "|", "&&") 
.SS "\fBt_token_type\fP t_operator::type"
The token type corresponding to this operator 

.SH "Author"
.PP 
Generated automatically by Doxygen for 42sh from the source code\&.
.SH SEE ALSO
.BR 42sh.h (9),
.BR ast_display.c (9),
.BR ast.h (9),
.BR builtin.c (9),
.BR builtin_history.c (9),
.BR builtins.h (9),
.BR command_search.c (9),
.BR exec_command.c (9),
.BR exec_logical.c (9),
.BR exec_pipeline.c (9),
.BR exec_utils.c (9),
.BR executor.c (9),
.BR executor.h (9),
.BR expander.c (9),
.BR heredoc.c (9),
.BR history.c (9),
.BR history.h (9),
.BR lexer.c (9),
.BR lexer_display.c (9),
.BR lexer.h (9),
.BR lexer_operator.c (9),
.BR lexer_words.c (9),
.BR memory.c (9),
.BR parser_and_or.c (9),
.BR parser.c (9),
.BR parser_command.c (9),
.BR parser_group.c (9),
.BR parser.h (9),
.BR parser_heredoc.c (9),
.BR parser_list.c (9),
.BR parser_pipeline.c (9),
.BR signal_child.c (9),
.BR signal_exec.c (9),
.BR signals.h (9),
.BR t_ast (9),
.BR t_binary (9),
.BR t_cmd (9),
.BR t_group (9),
.BR t_parser (9),
.BR t_redir (9),
.BR t_shell (9),
.BR t_token (9)
